CREATE DATABASE NewShoreAir
USE NewShoreAir

CREATE TABLE TRANSPORT
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    FLIGHT_CARRIER VARCHAR(50) NOT NULL,
    FLIGHT_NUMBER VARCHAR(50) NOT NULL
)
CREATE NONCLUSTERED INDEX IX_Transport_FlightCarrier ON TRANSPORT(Flight_Carrier);


CREATE TABLE FLIGHT
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    TRANSPORT_ID INT FOREIGN KEY(TRANSPORT_ID) REFERENCES TRANSPORT(ID),
    DEPARTURE_STATION VARCHAR(50) NOT NULL,
    ARRIVAL_STATION  VARCHAR(50) NOT NULL,
    PRICE DECIMAL(9,2) NOT NULL
);

CREATE NONCLUSTERED INDEX IX_Flight_DepartureStation ON FLIGHT(DEPARTURE_STATION);
CREATE NONCLUSTERED INDEX IX_Flight_ARRIVAL_STATION ON FLIGHT(ARRIVAL_STATION);


CREATE TABLE JOURNEY
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    ORIGIN VARCHAR(50) NOT NULL,
    DESTINATION VARCHAR(50) NOT NULL,
    PRICE DECIMAL(9,2) NOT NULL 
)
CREATE NONCLUSTERED INDEX IX_Journey_Origin_Destination ON JOURNEY(DESTINATION);
CREATE NONCLUSTERED INDEX IX_Journey_Origin_Origin ON JOURNEY(ORIGIN);

CREATE TABLE JOURNEY_FLIGHT
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    JOURNEY_ID INT FOREIGN KEY(JOURNEY_ID) REFERENCES JOURNEY(ID),
    FLIGHT_ID INT FOREIGN KEY(FLIGHT_ID) REFERENCES FLIGHT(ID)
)

CREATE NONCLUSTERED INDEX IX_JourneyFlight_FlightID ON JOURNEY_FLIGHT(FLIGHT_ID);




